controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_employee_create:
    path: /api/employee
    controller: App\Controller\EmployeeController::createEmployee
    methods: POST

api_working_time_create:
    path: /api/working-time
    controller: App\Controller\WorkingTimeController::createWorkTime
    methods: POST
